# Defined anchors for re-usable components
references:
  restore_cache: &restore_cache
    restore_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
  install_dependencies: &install_dependencies
    run: 
      name: Install Python deps in a venv
      command: |
        python3 -m venv venv
        . venv/bin/activate
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install setuptools wheel twine
  save_cache: &save_cache
    save_cache:
      key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      paths:
        - "venv"
  run_unittests: &run_unittests
    run:
      name: Run unittests
      command: |
        . venv/bin/activate
        python3 -m unittest discover
  init_pypirc: &init_pypirc
    run:
      name: init .pypirc
      command: |
        echo -e "[pypi]" >> ~/.pypirc
        echo -e "username = __token__" >> ~/.pypirc
        echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
  build_publish: &build_publish      
    run:
      name: Build and publish
      command: |
        . venv/bin/activate
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*


# Actual jobs
version: 2
jobs:
    test_all:
      filters:  # using regex filters requires the entire branch to match
          branches:
            only:  # only branches matching the below regex filters will run
              - develop
      working_directory: ~/pycorr
      docker:
        - image: circleci/python:3.7.1-stretch        
      steps:
        - checkout
        - <<: *restore_cache
        - <<: *install_dependencies
        - <<: *save_cache
        - <<: *run_unittests
    
    pypi_publish:
      filters:
          branches:
            only: 
              - master
      working_directory: ~/pycorr
      docker:
        - image: circleci/python:3.7.1-stretch
      steps:
        - checkout
        - <<: *restore_cache
        - <<: *install_dependencies
        - <<: *save_cache
        - <<: *run_unittests
        - <<: *init_pypirc
        - <<: *build_publish

# defined workflows            
workflows:
  version: 2
  test_dev:
    jobs:
      - test_all
  publish_master:
    jobs:
      - pypi_publish




